export const WEATHER_CODE = {
    0: 'Cielo Azul',
    1: 'Principalmente claro', 
    2: 'Parcialmente nublada',
    3: 'Nublado',
    45: 'Niebla', 
    48: 'Depositando niebla de escarcha',
    51: 'Llovizna de luz',
    53: 'Llovizna moderada',
    55:	'Llovizna de intensidad densa',
    56: 'Luz de llovizna helada',
    57: 'Llovizna Engelante intensidad densa',
    61: 'Lluvia Ligera',
    63: 'Lluvia moderada',
    65:	'Lluvia de gran intensidad',
    66: 'Lluvia helada Ligera',
    67:	'Lluvia helada de gran intensidad',
    71: 'Caída de nieve Ligera',
    73: 'Caída de nieve moderada',
    75:	'Caída de nieve de gran intensidad',
    77:	'Granos de nieve',
    80: 'Chubascos de lluvia Ligera',
    81: 'Lluvias moderadas',
    82:	'Lluvias violentas',
    85: 'Chubascos de nieve leves',
    86: 'Chubascos de nieve fuertes',
    95: 'Tormenta eléctrica Ligera o moderada',
    96: 'Tormenta ligera',
    99:	'Tormenta con fuerte granizo'
}